### ISSUE TITLE
Create sphinx docs

### ISSUE THREAD

**Issue by quim0** [radareorg/radare2-r2papi#17]
We should document current methods and classes, and generate docs based on that.
Probably sphinx is the best choice, it can be integrated with beta r2 website.

**Comment by quim0** [comment]
Compiling documentation and visualizing:

``` shell
$ cd python/docs
$ make html
$ $BROWSER _build/html/index.html
```

**Comment by quim0** [comment]
In case anyone wants to see the docs, they're online at https://farlopa.gratis/r2api-docs/
As everything in this repo, it's still WIP

**Comment by trufae** [comment]
Docs are now available via gh pages too
