### ISSUE TITLE
Export graph api also

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2-r2papi#7]
To get the petgraph representation of radare2 graph commands output, like `agj` or `dmhg`.

**Comment by sushant94** [comment]
This is done in radeco-lib for callgraph. Do you want to move that here?

**Comment by XVilka** [comment]
can be useful for other applications, apart from radeco.

**Comment by sushant94** [comment]
Yes, but there are a few structs used that only make sense for radeco. In this case, I'll probably have to convert it to a generic before adding it to this.

Also, I'm not sure if having all r2pipe-api in one repo makes sense. imo, it should be on a per-language basis.

**Comment by trufae** [comment]
Done in typescript
